In [11]:
import random
from deap import gp as deap_gp
import gp
from data import get_embeddings

In [2]:
seed = 1126
random.seed(seed)

In [3]:
class config:
    def __init__(
        self,
        algorithm,
        embedding_type,
        dimension,
        population_size,
        crossover_method,
        cross_prob,
        mut_prob,
        num_generations,
        num_evaluations,
        debug,
    ):
        self.algorithm = algorithm
        self.embedding_type = embedding_type
        self.dimension = dimension
        self.population_size = population_size
        self.crossover_method = crossover_method
        self.cross_prob = cross_prob
        self.mut_prob = mut_prob
        self.num_generations = num_generations
        self.num_evaluations = num_evaluations
        self.debug = debug

In [4]:
Config = config("simple_gp",
        "word2vec",
        10,
        100,
        "cx_random",
        0.9,
        0.1,
        100,
        1000,
        False)

In [6]:
data, embeddings, embedding_model = get_embeddings(
        Config.embedding_type, Config.dimension
    )

cx_method = gp.get_cx_num(Config.crossover_method)

# Initialize instance weights
data["weights"] = 1.0 / len(data)
data["weights_update"] = 1.0 / len(data)

boosting_interval = 10  # Boosting interval

ensemble = []  # Ensemble to store the best individuals

gpab = gp.GP(
    Config.algorithm,
    Config.embedding_type,
    Config.dimension,
    Config.population_size,
    cx_method,
    Config.cross_prob,
    Config.mut_prob,
    Config.num_generations,
    Config.num_evaluations,
    data,
    embeddings,
)
gpab.initialize_pop()

In [21]:
gpab.inputword

69542                [teary, adler, tells, of, family]
142293    [ethiopia, tigray, refugees, sudan, eritrea]
188137           [vic, corruption, fighter, tells, of]
123849                [fowler, fury, set, for, crisis]
18781                 [love, pleads, guilty, to, drug]
                              ...                     
166473      [tendulkar, confident, ahead, of, special]
265261               [russia, to, build, reactors, in]
17271           [hotel, for, former, academy, cinemas]
7032             [voss, out, fletcher, faces, nervous]
52567       [abbott, backs, morrisons, asylum, seeker]
Name: 0, Length: 2669, dtype: object

In [20]:
gpab.inputword.iloc[0]

['teary', 'adler', 'tells', 'of', 'family']

In [39]:
str(one_tree)

'protected_div(square(c), b)'

In [25]:
one_tree = gpab.pop[0]
func = deap_gp.compile(one_tree, gpab.pset)
func

<function <lambda>(a, b, c, d, e)>

In [49]:
one_sentence = gpab.inputword.iloc[0]
one_sentence

['teary', 'adler', 'tells', 'of', 'family']

In [50]:
[gpab.embeddings[char] for char in one_sentence]

[array([ 0.11124628, -0.03967056,  0.50254434, -0.04171659,  0.14895481,
         0.19047628,  0.05341799,  0.37907898, -0.23943269, -0.20617917],
       dtype=float32),
 array([ 1.109828  , -0.16263524,  0.6663412 , -1.691218  ,  0.04622373,
        -0.3450133 ,  0.35859436,  1.5889462 ,  0.04097964, -0.20548895],
       dtype=float32),
 array([ 1.9017696 , -0.95221716,  7.549865  ,  2.2828684 , -1.8736454 ,
        -1.5935872 ,  2.3461266 , -1.0195208 , -0.6089801 ,  5.164193  ],
       dtype=float32),
 array([ 0.58717966,  3.8716216 ,  0.51241934, -0.38943842,  0.11221036,
        -2.464539  , -0.46076557,  1.6559341 ,  0.10535118,  0.5409529 ],
       dtype=float32),
 array([ 2.8095908 ,  1.0558096 , -1.1745657 , -3.8866315 , -1.1910428 ,
        -1.4504529 , -2.4664845 ,  3.022177  ,  0.12800886, -0.97887594],
       dtype=float32)]

In [53]:
len([gpab.embeddings[char] for sentence in gpab.inputword for char in sentence])


13345

In [28]:
y_pred = [func(words.split()) for words in gpab.inputword]
y_pred

AttributeError: 'list' object has no attribute 'split'

In [13]:
def update_weight(trees):
    errors = []
    for idx, tree in enumerate(trees.pop):
        func = deap_gp.compile(tree, trees.pset)
        print(f"tree: {tree}")
        print(f"func: {func}")
        words = trees.inputwords
        # y_pred = (func(a, b, c, d, e))
        # y_true = (trees.embeddings[trees.realword.iloc[idx]])

        # # Calculate the prediction error (e.g., Euclidean distance)
        # error = np.linalg.norm(y_true - y_pred)
        # # print(f"error: {error}")
        # errors.append(error)
    return errors

error = update_weight(gpab)

tree: protected_div(square(c), b)
func: <function <lambda> at 0x7f5362544ee0>
tree: protected_div(protected_div(e, b), protected_sqrt(multiply(a, a)))
func: <function <lambda> at 0x7f53629a6820>
tree: add(multiply(protected_sqrt(e), subtract(d, c)), multiply(protected_sqrt(a), subtract(b, c)))
func: <function <lambda> at 0x7f5362544ee0>
tree: square(protected_sqrt(square(square(a))))
func: <function <lambda> at 0x7f53629a6820>
tree: subtract(e, b)
func: <function <lambda> at 0x7f5362544ee0>
tree: square(e)
func: <function <lambda> at 0x7f53629a6820>
tree: multiply(add(b, a), protected_div(b, d))
func: <function <lambda> at 0x7f5362544ee0>
tree: protected_div(subtract(square(e), protected_sqrt(c)), add(protected_sqrt(d), subtract(a, d)))
func: <function <lambda> at 0x7f5362996b80>
tree: protected_sqrt(multiply(subtract(b, d), b))
func: <function <lambda> at 0x7f5362544ee0>
tree: multiply(square(a), protected_div(square(e), subtract(b, d)))
func: <function <lambda> at 0x7f5362996b80>
tre

[]